HotelWeb/Pages/Booking/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BusinessObject.Model;
using DataAccess.Repository;
using HotelWeb.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HotelWeb.Pages.Booking
{
    public class CartModel : PageModel
    {
        private readonly IRoomRepository roomRepository;
        private readonly IRoomTypeRepository roomTypeRepository;
        private readonly IBookRoomRepository bookRoomRepository;
        private readonly ICouponRepository couponRepository;
        private readonly IRoomInBookingRepository roomInBookingRepository;
        public CartModel(IRoomRepository _roomRepository, IRoomTypeRepository _roomTypeRepository, IBookRoomRepository _bookRoomRepository, ICouponRepository _couponRepository, IRoomInBookingRepository _roomInBookingRepository)
        {
            roomRepository = _roomRepository;
            roomTypeRepository = _roomTypeRepository;
            bookRoomRepository = _bookRoomRepository;
            couponRepository = _couponRepository;
            roomInBookingRepository = _roomInBookingRepository;
        }
        public IList<Cart> Cart { get; set; }
        [BindProperty]
        public Cart CartItem { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "Cmnd can not be empty")]
        [RegularExpression("[0-9]{9,12}", ErrorMessage = "Wrong format for Cmnd number")]
        public decimal? Cmnd { get; set; }
        public int? discount { get; set; }
        public decimal? TotalPrice { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "CheckIn can not be empty")]
        [DataType(DataType.Date)]
        public DateTime CheckIn { get; set; }
        [BindProperty]
        public BookRoom BookRoom { get; set; }
        [BindProperty]
        public Coupon Coupon { get; set; }


        [BindProperty]
        [Required(ErrorMessage = "CheckOut can not be empty")]
        [DataType(DataType.Date)]
        public DateTime CheckOut { get; set; }
        private decimal? GetTotalPrice(List<Cart> cart)
        {
            decimal? result = 0;
            foreach (Cart item in cart)
            {
                result += item.Amount;
            }
            return result;
        }
        private decimal? GetTotalPriceDiscount(List<Cart> cart, int? discound)
        {
            decimal? result = 0;
            foreach (Cart item in cart)
            {
                result += item.Amount;
            }
            return (result*discound)/100;
        }
        public IActionResult OnGet()
        {
            try
            {
           
                var cart = HttpContext.Session.GetComplexData<List<Cart>>("CART");
                var day = cart.Take(1).ToList();
                CartItem = cart.FirstOrDefault(x => x.RoomId != null);
                if (cart != null)
                {
                    foreach (var day1 in day)
                    {
                        CheckIn = day1.CheckIn;
                        CheckOut = day1.CheckOut;
                    }
                    TotalPrice = GetTotalPrice(cart);
                    Cart = cart;
                }
                return Page();
            }
            catch (Exception ex)
            {
             
            }
            return Page();
        }
        public IActionResult OnAddtoCart()
        {

            try
            {


            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return Page();
        }
        public IActionResult OnPostDelete(int Id)
        {
            //if (HttpContext.Session.GetString("EMAIL") == null)
            //{
            //    return RedirectToPage("/Login");
            //}


            var cart = HttpContext.Session.GetComplexData<List<Cart>>("CART");
            if (cart != null)
            {
                if (cart.Exists(i => i.RoomId == Id))
                {
                    var item = cart.FirstOrDefault(i => i.RoomId == Id);
                    cart.Remove(item);
                    if (cart.Count > 0)
                    {
                        HttpContext.Session.SetComplexData("CART", cart);
                    }
                    else
                    {
                        HttpContext.Session.Remove("CART");
                    }
                }
            }
            return RedirectToPage();
        }
        public IActionResult OnPostPayment()
        {
            var cart = HttpContext.Session.GetComplexData<List<Cart>>("CART");
            CartItem = cart.FirstOrDefault(x => x.RoomId != null);
            if (HttpContext.Session.GetString("EMAIL") == null)
            {
                return RedirectToPage("/Login");
            }
            if (Coupon.Id == null)
            {
         
                BookRoom bookroom = new BookRoom
                {
                    CouponId = Coupon.Id,
                    StarTime = CartItem.CheckIn.Date,
                    EndTime = CartItem.CheckOut.Date,
                    AccountId = int.Parse(HttpContext.Session.GetString("Id")),
                    Cmnd = BookRoom.Cmnd,
                    Status = "BOOKED",
                    Total =  GetTotalPrice(cart)
            };
                bookRoomRepository.AddBookRoom(bookroom);
                List<BookRoom> BookRoomList = bookRoomRepository.GetBookRooms().ToList();
                BookRoom newItem = BookRoomList.LastOrDefault(x => x.Id != null);
                foreach (var item in cart)
                {
                    RoomInBooking roominbooking = new RoomInBooking
                    {
                        BookRoomId = newItem.Id,
                        RoomId = item.RoomId
                    };
                    roomInBookingRepository.AddRoominBooking(roominbooking);
                  
                }
                HttpContext.Session.Remove("CART");
                TempData["Message"] = "Payment successfully";
                return RedirectToPage("./Shopping");
            } 

            else
            {
                IEnumerable<Coupon> coupons = couponRepository.GetCoupons();
                Coupon coupon = coupons.SingleOrDefault(mb => mb.Id.Equals(Coupon.Id));
                if (coupon != null)
                {
                    Coupon = couponRepository.GetCouponById(Coupon.Id);
                    BookRoom bookroom = new BookRoom
                    {
                        CouponId = Coupon.Id,
                        StarTime = CartItem.CheckIn.Date,
                        EndTime = CartItem.CheckOut.Date,
                        AccountId = int.Parse(HttpContext.Session.GetString("Id")),
                        Cmnd = BookRoom.Cmnd,
                        Status = "BOOKED",
                        Total = GetTotalPrice(cart) - GetTotalPriceDiscount(cart, coupon.Discount)
                    };
                    bookRoomRepository.AddBookRoom(bookroom);
                    List<BookRoom> BookRoomList = bookRoomRepository.GetBookRooms().ToList();
                    BookRoom newItem = BookRoomList.LastOrDefault(x => x.Id != null);
                    foreach (var item in cart)
                    {
                        RoomInBooking roominbooking = new RoomInBooking
                        {
                            BookRoomId = newItem.Id,
                            RoomId = item.RoomId
                        };
                        roomInBookingRepository.AddRoominBooking(roominbooking);
                        
                    }
                    HttpContext.Session.Remove("CART");
                    TempData["Message"] = "Payment successfully";
                    return RedirectToPage("./Shopping");
                }
                else
                {
                    ViewData["ErrorMessage"] = "Coupon not Exists";
                    
                    var day = cart.Take(1).ToList();
                  
                    if (cart != null)
                    {
                        foreach (var day1 in day)
                        {
                            CheckIn = day1.CheckIn;
                            CheckOut = day1.CheckOut;
                        }
                        TotalPrice = GetTotalPrice(cart);
                        Cart = cart;
                    }
                    return Page();
                }
            }
            
        

            return RedirectToPage();
        }
    }
}

HotelWeb/Pages/Booking/RoomDetail.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BusinessObject.Model;
using DataAccess.Repository;
using HotelWeb.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;


namespace HotelWeb.Pages.Booking
{
    public class RoomDetailModel : PageModel
    {
        private readonly IRoomRepository roomRepository;
        private readonly IRoomTypeRepository roomTypeRepository;
        
        public RoomDetailModel(IRoomRepository _roomRepository, IRoomTypeRepository _roomTypeRepository)
        {
            roomRepository = _roomRepository;
            roomTypeRepository = _roomTypeRepository;
          
        }
        [BindProperty]
        [Required(ErrorMessage = "CheckIn can not be empty")]
        [DataType(DataType.Date)]
        public DateTime CheckIn { get; set; }
        [BindProperty]
        public IList<RoomType> RoomTypeList { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "CheckOut can not be empty")]
        [DataType(DataType.Date)]
        public DateTime CheckOut { get; set; }
        [BindProperty]
        public Room Room { get; set; }
        public TimeSpan ts;
        public  IActionResult OnGet(int id,DateTime In, DateTime Out)
        {
           
            try
            {
                RoomTypeList = roomTypeRepository.GetRoomsType().ToList();
                Room = roomRepository.GetRoomById(id);      
                CheckIn = In;
                CheckOut = Out;
                ts = CheckOut.Subtract(CheckIn);
             
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return Page();
        }
        public IActionResult OnPostAddtoCart()
        {   
            try
            {
                ts = CheckOut.Subtract(CheckIn);
                var cart = HttpContext.Session.GetComplexData<List<Cart>>("CART");
                var item = new Cart
                {
                    RoomId = Room.Id,
                    Amount = Room.Amount * decimal.Parse(ts.Days.ToString()),
                    Image = Room.Image,
                    CheckIn = CheckIn,
                    CheckOut = CheckOut,
                    Title = Room.Title
                };
                if (cart != null)
                {
                    Cart Day = cart.FirstOrDefault(i => i.CheckIn.Equals(CheckIn) && i.CheckOut.Equals(CheckOut));
                    Cart Id = cart.SingleOrDefault(i => i.RoomId.Equals(Room.Id));
                    if (Id != null )
                    {
                        // If item is already exist in cart
                      //  Cart itemIdInCart = cart.SingleOrDefault(i => i.CheckIn.Equals(item.CheckIn) && i.CheckOut.Equals(item.CheckOut));
                      //  Cart itemDayInCart =   cart.SingleOrDefault(i => i.CheckIn.Equals(item.CheckIn) && i.CheckOut.Equals(item.CheckOut));         
                            TempData["Message"] = "This room is Exists in shopping cart";           
                    }
                    else if(Day != null)
                    {
                        cart.Add(item);
                        TempData["Message"] = "Add Room to cart successfully";
                    }
                    else {
                        TempData["Message"] = "Check In and Check Out not same";
                    }
                    HttpContext.Session.SetComplexData("CART", cart);
                }
                else //When cart is null -> create new cart
                {
                    var list = new List<Cart>();
                    list.Add(item);
                    HttpContext.Session.SetComplexData("CART", list);
                    TempData["Message"] = "Add product to cart successfully";
                }

                return RedirectToPage("./Shopping");
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return Page();
        }
        
    }
}

#region ExtendSession
public static class SessionExtensions
{
    public static T GetComplexData<T>(this ISession session, string key)
    {
        var data = session.GetString(key);
        if (data == null)
        {
            return default(T);
        }
        return JsonConvert.DeserializeObject<T>(data);
    }

    public static void SetComplexData(this ISession session, string key, object value)
    {
        session.SetString(key, JsonConvert.SerializeObject(value));
    }
}
#endregion

HotelWeb/Pages/CouponManagement/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BusinessObject.Model;
using DataAccess.Repository;

namespace HotelWeb.Pages.CouponManagement
{
    public class IndexModel : PageModel
    {

        private readonly ICouponRepository couponRepository;

        public IndexModel(ICouponRepository _couponRepository)
        {

            couponRepository = _couponRepository;
        }
        [BindProperty]
        public Coupon Coupon { get; set; }

        public IList<Coupon> CouponList { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        public IActionResult OnGet()
        {
            try
            {
                CouponList = couponRepository.GetCoupons().ToList();
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }

            return Page();
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            try
            {
                Coupon coupon = new Coupon
                {
                    Id = Coupon.Id,               
                    Description = Coupon.Description,
                    Discount = Coupon.Discount
                };
                couponRepository.AddCoupon(coupon);

            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return RedirectToPage("./Index");

        }
        public IActionResult OnPostSearch([FromForm] string SearchString)
        {
            if (!string.IsNullOrEmpty(SearchString))
            {
                CouponList = couponRepository.SearchByName(SearchString.ToLower().Trim());
            }
            else
            {
                CouponList = couponRepository.GetCoupons().ToList();
            }
            return Page();
        }
        public IActionResult OnPostDelete(string id)
        {
            try
            {
                Coupon couponid = couponRepository.GetCouponById(id);
   
                couponRepository.DeleteCoupon(couponid);

            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return RedirectToPage("./Index");

        }
    }
}

HotelWeb/Pages/Booking/Cart.cshtml
@page
@model HotelWeb.Pages.Booking.CartModel
@{
}
<style>
    #Delete {
        padding: 0 !important;
        border: none !important;
        background: none !important;
        outline: none !important;
        margin: 0 !important;
        color: #FF0000 !important;
        width: 25px !important;
    }
</style>

<div class="bg-dark text-center text-light mb-5 h3" style=" width: 100%; height:300px">
    <h2 style="padding-top: 130px;"> Shopping Cart => Booking => Check In => Check Out</h2>
</div>

<div class="container">
    @if (Model.Cart != null)
    {
        <div class="row">
            <div class="col-8">


                <table class="table table-striped table-hover">

                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Cart[0].Image)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Cart[0].Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Cart[0].Amount)
                            </th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Cart)
                        {
                            <tr>
                                <td>
                                    <img src="~/img/@item.Image" alt="image" height="80" width="80" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Amount)
                                </td>
                                <td>
                                    <div class="col-sm-2">
                                        <form method="post" asp-page-handler="Delete" asp-route-id="@item.RoomId" class="ml-0" onclick="return confirm('Are you sure you want to Delete this?')">
                                            <div class="row">
                                                <div>
                                                    <button id="Delete" class="" type="submit" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE5C9;</i></button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            }
                    <tbody>
                </table>
                
            </div>
            <div class="col-4 ">
                @if (ViewBag.ErrorMessage != null)
                {
                    <div class="alert alert-danger text-center" role="alert">
                        @ViewBag.ErrorMessage
                    </div>}
                <form method="post" asp-page-handler="Payment">
                    <div style="padding: 20px; height: auto; width:auto" class="border">
                        <p class="h3 font-weight-bold">Cart Total:</p>

                        <div class="   w-100" style="height: auto">
                            <p class="float-left font-weight-bolder">Price</p>
                            <ul class="float-right border-bottom w-100 text-success mb-2 pb-2"   style="height: auto ; list-style-type: none">
                                @foreach (var item in Model.Cart)
                                {
                                <li class="">
                                 
                                    <p class="  text-success">@item.Amount.ToString().000đ</p>
                                </li>
                                }
                            </ul>

                        </div>
                        <div class="border-bottom  mt-3 pb-2 mb-3 w-100" style="height: 50px; clear: both">
                            <p class="float-left pb-2 font-weight-bolder" style="height: 50px">CheckIn</p>
                            <p class="float-right  text-success">@Model.CheckIn.ToShortDateString()</p>
                        </div>
                        <div class="border-bottom  pb-2 mb-3 w-100" style="height: 50px">
                            <p class="float-left pb-2 font-weight-bolder" style="height: 50px">Checkout</p>
                            <p class="float-right  text-success">@Model.CheckOut.ToShortDateString()</p>
                        </div>
                        <div class="border-bottom pb-5 mb-5 w-100">
                            <p class="float-left h4 font-weight-bolder">Total</p>
                            <p class="float-right  text-success">@Model.TotalPrice.ToString().000đ</p>
                        </div>
                        <div class="form-group">
                            <label asp-for="BookRoom.Cmnd" class="control-label"></label>
                            <input asp-for="BookRoom.Cmnd" class="form-control" />
                            <span asp-validation-for="BookRoom.Cmnd" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Coupon</label>
                            <input asp-for="Coupon.Id" class="form-control" />
                            <span asp-validation-for="Coupon.Id" class="text-danger"></span>
                        </div>
                        <input type="hidden" asp-for="CartItem.CheckIn" class="form-control" />
                        <input type="hidden" asp-for="CartItem.CheckOut" class="form-control" />
                        <button class="w-100 btn btn-success text-light h4">
                            Proceed to Booked
                        </button>

                    </div>
                </form>
            </div>
        </div>
            }
            else
            {
                <div class="h1"> Not Items</div>
            }
    </div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HotelWeb/Pages/Booking/RoomDetail.cshtml
@page
@model HotelWeb.Pages.Booking.RoomDetailModel
@{
}
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<div class="container">
    <form method="post" asp-page-handler="AddtoCart">
        <div class="row" style="margin-top: 120px">

            <div class="col-6">
                <img src="~/img/@Model.Room.Image" width="450" height="600" />
                <input asp-for="Room.Image" type="hidden" class="form-control" />
                <input asp-for="Room.Title" type="hidden" class="form-control" />
                <input asp-for="Room.Amount" type="hidden" class="form-control" />
                <input asp-for="Room.Id" type="hidden" class="form-control" />
            </div>
            <div class="col-6">
                <p class="h2 font-weight-bold">   Room:  @Model.Room.Title </p>
                <p class="h5 font-weight-bold" style="color: #ADD8E6">    Price :  @(Model.Room.Amount * decimal.Parse(Model.ts.Days.ToString()) ).000.000Đ / @Model.ts.Days.ToString() Month</p>

                @foreach (var item in Model.RoomTypeList)
                {
                    if (item.Id == Model.Room.RoomTypeId)
                    {
                        <p class="h5 font-weight-bold" style="color: #ADD8E6"> Type : @item.Title   </p>
                    }

                }

                <div>
                    Room amenities
                </div>
                <ul style="list-style: none !important;">
                    <li>Các vật dụng hiện có</li>
                    <li>
                        2 rooms 
                        2 toilets
                        1 balcony
                    </li>
                    <li>Đồng hồ nước riêng</li>
                </ul>
                <p>
                    Description : @Model.Room.Description
                </p>
                <div class="form-group">
                    <label asp-for="CheckIn" class="control-label"></label>
                    <input type="hidden" asp-for="CheckIn" class="form-control" />
                    <input disabled asp-for="CheckIn" class="form-control" />
                    <span asp-validation-for="CheckIn" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CheckOut" class="control-label"></label>
                    <input type="hidden" asp-for="CheckOut" class="form-control" />
                    <input disabled asp-for="CheckOut" class="form-control" />
                    <span asp-validation-for="CheckOut" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add To Cart" class="btn btn-primary" />
                </div>
            </div>

        </div>
    </form>
</div>

HotelWeb/Pages/Booking/Shopping.cshtml
@page
@model HotelWeb.Pages.Booking.ShoppingModel
@{
}
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        list-style: none;
        text-decoration: none;
        font-family: arial;
    }

    body {
    
    }

    .wrapper {
        position: relative;
    }

    .sidebar {
        position: fixed;
        height: 100%;
        width: 450px;
    }
    #search{
        margin-top: 100px;
    }
    #items {
        height: 100%;
        padding:0px;
        margin: 0px;
    }
</style>
<div class="container-fluid">
    
        <div class="row ">
            <div class="col-3 border-right position-fixed  h-100" style="height: 100%; width:100%;">
                @if (ViewBag.ErrorMessage != null)
                {
                    <div class="alert alert-danger text-center" role="alert">
                        @ViewBag.ErrorMessage
                    </div>}
                <form method="post" asp-page-handler="Search">
                    <div style="margin-left: 0px" class="">
                        <h2 class="text-center" style="margin-top:64px;"> Filter </h2>
                        <div class="text-center" id="search">

                            Search Rent Room:
                            <input asp-for="SearchString" style="margin-bottom: 10px" class="form-control" />
                            <span asp-validation-for="SearchString" class="text-danger" style="margin-top:10px"></span>

                            <div class="form-group">
                                <label asp-for="Room.RoomTypeId" class="control-label"></label>
                                <select asp-for="Room.RoomTypeId" class="form-control">
                                    <option value="">All</option>
                                    @foreach (var item in Model.RoomTypeList)
                                    {
                                        <option value="@item.Id"> @item.Title</option>
                                    }
                                </select>
                                <span asp-validation-for="Room.RoomTypeId" class="text-danger"></span>
                            </div>


                            <div class=" mt-1">
                                <div class="form-group">
                                    <label asp-for="CheckIn" class="control-label"></label>
                                    <input asp-for="CheckIn" class="form-control" />
                                    <span asp-validation-for="CheckIn" class="text-danger"></span>
                                </div>
                            </div>

                            <div class=" mt-1">
                                <div class="form-group">
                                    <label asp-for="CheckOut" class="control-label"></label>
                                    <input asp-for="CheckOut" class="form-control" />
                                    <span asp-validation-for="CheckOut" class="text-danger"></span>
                                </div>
                            </div>

                            <div class=" mt-1">
                                <button class="btn btn-primary" type="submit">Filter</button>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-9 " id="items" style="height: 100%; margin-left:450px">


                @foreach (var item in Model.RoomList)
                {
                    <div class="  mb-5">
                        <div class=" border rounded row" style=" height:400px ; margin-top:10px; margin-bottom:30px; margin-left:50px; margin-right:20px">

                            <div class="col-4" style="padding: 10px">
                                <img class="" src="~/img/@item.Image" style="height:100%; width:100%;" alt="Card image cap">
                            </div>
                            <div class="col-8">
                                                         
                                <h2 class=" mt-1 mb-1 text-center card-title"> @item.Title</h2>
                                @foreach (var type in Model.RoomTypeList)
                                {
                                    if (item.RoomTypeId == type.Id)
                                    {
                                        <p class="card-text">Type: @type.Title</p>
                                    }
                                }

                                <p class="card-text">Start rent : @Model.CheckIn.ToShortDateString() </p>
                                <p class="card-text">Stop rent (Expeceted) : @Model.CheckOut.ToShortDateString() </p>
                                <p class="card-text">Approximately Rent: @(@item.Amount * decimal.Parse(Model.ts.Days.ToString())).000.000VNĐ</p>
                                <p class="card-text"></p>
                                @if (Model.first.Any(x => x.Id == item.Id) == true )
                                {
                                    <button type="submit"  disabled asp-route-id="@item.Id" asp-route-in="@Model.CheckIn" asp-route-out="@Model.CheckOut" id="Booking" class="btn btn-danger">Not Available</button>
                                }
                                else
                                {
                               <a  asp-page="./RoomDetail"  asp-route-id="@item.Id" asp-route-in="@Model.CheckIn" asp-route-out="@Model.CheckOut" id="Booking" class="btn btn-primary">Details</a>
                                }

                            </div>
                        </div>
                    </div>

                }

                

                <div class="container border-top">
                &copy; Copyright 2023 RENTZ VIETNAM. Powered by RENTZ
                </div>

            </div>
        </div>
</div>
<script type="text/javascript">
        window.onload = function() {
            if ('@TempData["Message"]' != "") {
                alert('@TempData["Message"]');
            }
    };
    

</script>