HotelWeb/Pages/Profile/ChangePassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BusinessObject.Model;
using DataAccess.Repository;
using HotelWeb.Utils.FileUploadService;
using HotelWeb.Validation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HotelWeb.Pages.Profile
{
    public class ChangePasswordModel : PageModel
    {
        private readonly IAccountRepository accountRepository;
        private readonly IFileUploadService fileUploadService;
        public ChangePasswordModel(IAccountRepository _accountRepository, IFileUploadService _fileUploadService)
        {
            accountRepository = _accountRepository;
            fileUploadService = _fileUploadService;
        }
        [BindProperty]
        public Account Account { get; set; }


        [DataType(DataType.Upload)]
        [Display(Name = "Choose an image to upload")]
        [ProductImageValidation]
        [BindProperty]
        public IFormFile ImageFile { get; set; }

        [BindProperty]
        [StringLength(maximumLength: 20,
 ErrorMessage = "Password's lenght must be between 6-20",
 MinimumLength = 6)]
        [Required(ErrorMessage = "Confirm Password is required")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [BindProperty]
        [StringLength(maximumLength: 20,
        ErrorMessage = "Password's lenght must be between 6-20",
        MinimumLength = 6)]
        [Required(ErrorMessage = " Password is required")]
        public string Password { get; set; }

        [BindProperty]
        [StringLength(maximumLength: 20,
        ErrorMessage = "Password's lenght must be between 6-20",
        MinimumLength = 6)]
        [Required(ErrorMessage = "Current Password is required")]
        public string CurrentPassword { get; set; }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("ROLE") == null)
            {
                return Page();
            }
            try
            {
                string Id = HttpContext.Session.GetString("Id");
                Account = accountRepository.GetProfile(int.Parse(Id));
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }

            return Page();
        }

        public async Task<IActionResult> OnPostCreate()
        {
            try
            {

                if (CurrentPassword == Account.Password)
                {
                    ViewData["Message"] = "Successfully";
                    accountRepository.ChangePassword(Account.Id, Password);
                    return Page();
                }
                else
                {
                    ViewData["ErrorMessage"] = "Current Password not same";                   
                    return Page();
                }

                return Page();
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                return Page();
            }
        }
    }
}

HotelWeb/Pages/Profile/History.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessObject.Model;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HotelWeb.Pages.Profile
{
    public class HistoryModel : PageModel
    {
        private readonly IBookRoomRepository bookRoomRepository;
        private readonly IRoomInBookingRepository roomInBookingRepository;
        private readonly IRoomRepository roomRepository;
        public HistoryModel(IRoomRepository _roomRepository, IBookRoomRepository _bookRoomRepository, IRoomInBookingRepository _roomInBookingRepository )
        {
           
            bookRoomRepository = _bookRoomRepository;
            roomInBookingRepository = _roomInBookingRepository;
            roomRepository = _roomRepository;
        }
        public IList<BookRoom> BookRoom { get; set; }
        public IList<RoomInBooking> RoomInBookings { get; set; }
        public IList<Room> Room { get; set; }
        public IActionResult OnGet()
        {
            try
            {
                if (HttpContext.Session.GetString("ROLE") != "Customer")
                {
                    return RedirectToPage("./Login");
                }
                BookRoom = bookRoomRepository.GetHistory(int.Parse(HttpContext.Session.GetString("Id")));
                RoomInBookings = roomInBookingRepository.GetRooms().ToList();
                Room = roomRepository.GetRooms().ToList();
            }
            catch
            {

            }
            return Page();
        }
        public IActionResult OnPostCancel(int id)
        {
            try
            {
                bookRoomRepository.UpdateStatusCancel(id);
                TempData["Message"] = "Cancel Finsish";
                return RedirectToPage("./History");
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                return RedirectToPage("./History");
            }
        }
    }
}

HotelWeb/Pages/Profile/MyProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BusinessObject.Model;
using DataAccess.Repository;
using HotelWeb.Utils.FileUploadService;
using HotelWeb.Validation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HotelWeb.Pages.Profile
{
    public class MyProfileModel : PageModel
    {

        private readonly IAccountRepository accountRepository;
        private readonly IFileUploadService fileUploadService;
        public MyProfileModel(IAccountRepository _accountRepository, IFileUploadService _fileUploadService)
        {
            accountRepository = _accountRepository;
            fileUploadService = _fileUploadService;
        }
        [BindProperty]
        public Account Account { get; set; }


        [DataType(DataType.Upload)]
        [Display(Name = "Choose an image to upload")]
        [ProductImageValidation]
        [BindProperty]
        public IFormFile ImageFile { get; set; }

      
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("ROLE") == null)
            {
                return Page();
            }
            try
            {
                string Id = HttpContext.Session.GetString("Id");
                Account = accountRepository.GetProfile(int.Parse(Id));
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }

            return Page();
        }

        public async Task<IActionResult> OnPostCreate()
        {
            try
            {
         
                Account acc = new Account
                {
                    Id = Account.Id,
                    Email = Account.Email,
                    Password = Account.Password,
                    Fullname = Account.Fullname,
                    Gender = Account.Gender,
                    Phone = Account.Phone,
                    IsEmployee = Account.IsEmployee,
                    Avartar = Account.Avartar,
                    Active = Account.Active
                    
                };
                if (ImageFile != null)
                {
                    await fileUploadService.UploadFileAsync(ImageFile);
                    acc.Avartar = ImageFile.FileName;
                }
                HttpContext.Session.SetString("Avatar", acc.Avartar);
                HttpContext.Session.SetString("EMAIL", acc.Fullname);
                accountRepository.UpdateMember(acc);
                return Page();
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                return Page();
            }
        }

    }
}

HotelWeb/Pages/Profile/ChangePassword.cshtml
@page
@model HotelWeb.Pages.Profile.ChangePasswordModel
@{
}
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<style>
    #banner {
        box-shadow: tomato;
        display: grid;
        grid-template-columns: 418px 300px;
        width: 718px;
        height: 512px;
        z-index: -1;
        position: absolute;
        left: 50%;
        top: 60%;
        transform: translate(-50%, -70%);
        filter: drop-shadow(0 0 5px #F2E9E4);
        z-index: 10;
    }

    #hien {
        position: absolute;
        left: 50%;
        filter: drop-shadow(0 0 5px #F2E9E4);
        z-index: 10;
    }

    body {
    }

    #login {
        text-align: center;
        background-color: white;
    }

    #form-input {
        position: relative;
        z-index: 2;
        border: 2px solid rgba(211, 208, 208, 0.658);
        border-radius: 4px;
        height: 50px;
        padding: 0 20px;
        transition: 0.25s ease;
        margin-bottom: 25px;
        user-select: none;
    }

        #form-input:focus {
            --tw-text-opacity: 1;
            border-color: rgba(37, 99, 235, var(--tw-text-opacity));
            outline: none;
            user-select: none;
        }

    #form-field {
        position: relative;
        z-index: 1;
    }

    #form-label {
        position: absolute;
        top: 30%;
        transform: translateY(-50%);
        left: 0px;
        user-select: none;
        color: rgba(207, 195, 195, 0.795);
        pointer-events: none;
        transition: 0.25s ease;
        padding-bottom: -20px;
        z-index: 2;
    }

    #form-input:not(:placeholder-shown) + #form-label, #form-input:focus + #form-label {
        top: 0px;
        left: -10px;
        user-select: none;
        display: inline-block;
        background-color: white;
        color: #575669;
    }

    #form-input:focus + #form-label {
        top: 0px;
        left: -10px;
        padding: 0px;
        display: inline-block;
        background-color: white;
        --tw-text-opacity: 1;
        color: rgba(37, 99, 235, var(--tw-text-opacity));
        user-select: none;
    }

    #form-field-invalid {
        position: relative;
        z-index: 1;
        color: red;
        user-select: none;
    }

    #form-input-invalid {
        position: relative;
        z-index: 2;
        border: 1px solid red;
        border-radius: 4px;
        height: 50px;
        padding: 0 20px;
        transition: 0.25s ease;
        margin-bottom: 25px;
        user-select: none;
    }

        #form-input-invalid:focus {
            --tw-text-opacity: 1;
            outline: none;
        }


    #form-label-invalid {
        position: absolute;
        top: 30%;
        transform: translateY(-50%);
        left: 0;
        user-select: none;
        color: red;
        pointer-events: none;
        transition: 0.25s ease;
        padding-bottom: -20px;
        z-index: 2;
        user-select: none;
    }

    #form-input-invalid:not(:placeholder-shown) + #form-label-invalid, #form-input-invalid:focus + #form-label-invalid {
        top: 0px;
        left: 0;
        padding: -10px;
        display: inline-block;
        background-color: white;
        color: red;
        user-select: none;
    }

    #form-input-invalid:focus + #form-label-invalid {
        top: 0px;
        left: -10px;
        padding: 0px;
        display: inline-block;
        background-color: white;
        --tw-text-opacity: 1;
        color: red;
        user-select: none;
    }

    #img {
        background-color: #BB9F66;
    }

    #login h2 {
        margin-top: 22px;
        color: #f66c08;
        font-size: 20px;
        line-height: 24px;
        margin-bottom: 25px;
    }

    #login h3 {
        margin-top: 22px;
        font-weight: 600;
        font-size: 20px;
        line-height: 24px;
        margin-bottom: 25px;
    }

    #login p {
        color: #575669;
        font-size: 11px;
        line-height: 13px;
        margin-bottom: 25px;
    }

    #log {
        border: 1px solid #eee;
        border-radius: 4px;
        width: 70%;
        color: white;
        height: 30px;
        background-color: #32437c;
        padding: 0 20px;
        transition: 0.25s ease;
        margin-bottom: 25px;
    }

        #log:focus-within {
            background-color: blue;
        }

    #gmail {
        text-align: left;
        border: 1px solid #eee;
        border-radius: 4px;
        width: 70%;
        height: 1000px;
        color: #0000008A;
        height: 30px;
        background-color: white;
    }

        #gmail svg {
            float: left;
        }

        #gmail div {
            float: left;
            padding-left: 10px;
        }

    #gg {
        padding-left: 5px;
    }


    #book {
        margin-top: 50px;
        margin-left: 9%;
        width: 249px;
        height: 400px;
    }

    body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }



    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }

    label {
        cursor: pointer;
        /* Style as you please, it will become the visible UI component. */
    }

    #upload-photo {
        opacity: 0;
        position: absolute;
        z-index: -1;
    }
</style>
<div class="container-xl px-4 mt-4">

    <nav class="nav nav-borders">
        <a class="nav-link  ms-0" asp-page="/Profile/MyProfile">Profile</a>
        <a class="nav-link active" asp-page="#">Change Pasword</a>
        <a class="nav-link" asp-page="/Profile/History">History</a>
    </nav>
    <hr class="mt-0 mb-4">
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger text-center" role="alert">
            @ViewBag.ErrorMessage
        </div>}
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
        </script>

    }
    <form method="post" enctype="multipart/form-data" asp-page-handler="Create">
        <div class="row">

            <div class="col-xl-4">
                <!-- Profile picture card-->
                <div class="card mb-4 mb-xl-0">
                    <div class="card-header">Profile Picture</div>
                    <div class="card-body text-center">
                        <!-- Profile picture image-->

                        <img src="~/img/@HttpContextAccessor.HttpContext.Session.GetString("Avatar")" class="img-account-profile  rounded-circle  mb-2" alt="Avatar" style="width: 300px; height: 300px;" class="avatar">
                        <input asp-for="Account.Avartar" type="hidden" class="form-control" />
                        <!-- Profile picture upload button-->
                    </div>
                </div>
            </div>
            <div class="col-xl-8">
                <!-- Account details card-->
                <div class="card mb-4">
                    <div class="card-header">Account Details</div>
                    <div class="card-body">

                        <!-- Form Group (username)-->
                        <div id="form-field" class="mb-3">
                            <input type="password" asp-for="CurrentPassword" id="form-input" style="width: 320px" placeholder=" " />
                            <label asp-for="CurrentPassword" style="margin-left:20px; " id='form-label'>Current Password</label>
                            <span asp-validation-for="CurrentPassword" class="text-danger"></span>
                        </div>
                        <div id="form-field" class="mb-3">
                            <input type="password" asp-for="Password" id="form-input" style="width: 320px" placeholder=" " />
                            <label asp-for="Password" style="margin-left:20px; " id='form-label'>New Password</label>
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div id="form-field" class="mb-3">
                            <input type="password" asp-for="ConfirmPassword" id="form-input" style="width: 320px" placeholder=" " />
                            <label asp-for="ConfirmPassword" style="margin-left:30px; " id='form-label'>Confirm Password</label>
                            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                        </div>
                        <input asp-for="Account.Id" type="hidden" class="form-control" />
                        <input asp-for="Account.Active" type="hidden" class="form-control" />
                        <input asp-for="Account.IsEmployee" type="hidden" class="form-control" />
                        <input asp-for="Account.Fullname" type="hidden" class="form-control" />
                        <input asp-for="Account.Email" type="hidden" class="form-control" />
                        <input asp-for="Account.Password" type="hidden" class="form-control" />
                        <!-- Form Row        -->
                        <!-- Save changes button-->
                        <div class="form-group">
                            <button style="padding: 20px 10px" type="submit" value="Save Changes" class="btn btn-primary">
                                Save Changes
                            </button>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </form>

</div>
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

HotelWeb/Pages/Profile/History.cshtml
@page
@model HotelWeb.Pages.Profile.HistoryModel
@{
}
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<style>
    #banner {
        box-shadow: tomato;
        display: grid;
        grid-template-columns: 418px 300px;
        width: 718px;
        height: 512px;
        z-index: -1;
        position: absolute;
        left: 50%;
        top: 60%;
        transform: translate(-50%, -70%);
        filter: drop-shadow(0 0 5px #F2E9E4);
        z-index: 10;
    }

    #hien {
        position: absolute;
        left: 50%;
        filter: drop-shadow(0 0 5px #F2E9E4);
        z-index: 10;
    }

    body {
    }

    #login {
        text-align: center;
        background-color: white;
    }

    #form-input {
        position: relative;
        z-index: 2;
        border: 2px solid rgba(211, 208, 208, 0.658);
        border-radius: 4px;
        height: 50px;
        padding: 0 20px;
        transition: 0.25s ease;
        margin-bottom: 25px;
        user-select: none;
    }

        #form-input:focus {
            --tw-text-opacity: 1;
            border-color: rgba(37, 99, 235, var(--tw-text-opacity));
            outline: none;
            user-select: none;
        }

    #form-field {
        position: relative;
        z-index: 1;
    }

    #form-label {
        position: absolute;
        top: 30%;
        transform: translateY(-50%);
        left: 0px;
        user-select: none;
        color: rgba(207, 195, 195, 0.795);
        pointer-events: none;
        transition: 0.25s ease;
        padding-bottom: -20px;
        z-index: 2;
    }

    #form-input:not(:placeholder-shown) + #form-label, #form-input:focus + #form-label {
        top: 0px;
        left: -10px;
        user-select: none;
        display: inline-block;
        background-color: white;
        color: #575669;
    }

    #form-input:focus + #form-label {
        top: 0px;
        left: -10px;
        padding: 0px;
        display: inline-block;
        background-color: white;
        --tw-text-opacity: 1;
        color: rgba(37, 99, 235, var(--tw-text-opacity));
        user-select: none;
    }

    #form-field-invalid {
        position: relative;
        z-index: 1;
        color: red;
        user-select: none;
    }

    #form-input-invalid {
        position: relative;
        z-index: 2;
        border: 1px solid red;
        border-radius: 4px;
        height: 50px;
        padding: 0 20px;
        transition: 0.25s ease;
        margin-bottom: 25px;
        user-select: none;
    }

        #form-input-invalid:focus {
            --tw-text-opacity: 1;
            outline: none;
        }


    #form-label-invalid {
        position: absolute;
        top: 30%;
        transform: translateY(-50%);
        left: 0;
        user-select: none;
        color: red;
        pointer-events: none;
        transition: 0.25s ease;
        padding-bottom: -20px;
        z-index: 2;
        user-select: none;
    }

    #form-input-invalid:not(:placeholder-shown) + #form-label-invalid, #form-input-invalid:focus + #form-label-invalid {
        top: 0px;
        left: 0;
        padding: -10px;
        display: inline-block;
        background-color: white;
        color: red;
        user-select: none;
    }

    #form-input-invalid:focus + #form-label-invalid {
        top: 0px;
        left: -10px;
        padding: 0px;
        display: inline-block;
        background-color: white;
        --tw-text-opacity: 1;
        color: red;
        user-select: none;
    }

    #img {
        background-color: #BB9F66;
    }

    #login h2 {
        margin-top: 22px;
        color: #f66c08;
        font-size: 20px;
        line-height: 24px;
        margin-bottom: 25px;
    }

    #login h3 {
        margin-top: 22px;
        font-weight: 600;
        font-size: 20px;
        line-height: 24px;
        margin-bottom: 25px;
    }

    #login p {
        color: #575669;
        font-size: 11px;
        line-height: 13px;
        margin-bottom: 25px;
    }

    #log {
        border: 1px solid #eee;
        border-radius: 4px;
        width: 70%;
        color: white;
        height: 30px;
        background-color: #32437c;
        padding: 0 20px;
        transition: 0.25s ease;
        margin-bottom: 25px;
    }

        #log:focus-within {
            background-color: blue;
        }

    #gmail {
        text-align: left;
        border: 1px solid #eee;
        border-radius: 4px;
        width: 70%;
        height: 1000px;
        color: #0000008A;
        height: 30px;
        background-color: white;
    }

        #gmail svg {
            float: left;
        }

        #gmail div {
            float: left;
            padding-left: 10px;
        }

    #gg {
        padding-left: 5px;
    }


    #book {
        margin-top: 50px;
        margin-left: 9%;
        width: 249px;
        height: 400px;
    }

    body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }



    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }

    label {
        cursor: pointer;
        /* Style as you please, it will become the visible UI component. */
    }

    #upload-photo {
        opacity: 0;
        position: absolute;
        z-index: -1;
    }
</style>
<div class="container-xl px-4 mt-4">

    <nav class="nav nav-borders">
        <a class="nav-link  ms-0" asp-page="/Profile/MyProfile">Profile</a>
        <a class="nav-link " asp-page="/Profile/ChangePassword">Change Pasword</a>
        <a class="nav-link active" asp-page="#">History</a>
    </nav>
    <hr class="mt-0 mb-4">
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger text-center" role="alert">
            @ViewBag.ErrorMessage
        </div>}
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
        </script>

    }

    <div class="row">
        <div class="col-xl-4">
            <!-- Profile picture card-->
            <div class="card mb-4 mb-xl-0">
                <div class="card-header">Profile Picture</div>
                <div class="card-body text-center">
                    <!-- Profile picture image-->

                    <img src="~/img/@HttpContextAccessor.HttpContext.Session.GetString("Avatar")" class="img-account-profile  rounded-circle  mb-2" alt="Avatar" style="width: 300px; height: 300px;" class="avatar">

                    <!-- Profile picture upload button-->
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <!-- Account details card-->
            <div class="card mb-4">
                <div class="card-header">History</div>
                @foreach (var item in Model.BookRoom)
                {



                    <div class="mb-5">
                        <div class=" border  text-center rounded row" style="  margin-top:10px; margin-bottom:10px; margin-left:30px; margin-right:20px">
                            <div class="container">
                                <h2 class=" mt-1 mb-1 text-center card-title">  @item.Id</h2>
                                <p class="card-text">CheckIn : @item.StarTime </p>
                                <p class="card-text">CheckOut : @item.EndTime </p>
                                <p class="card-text">
                                    Room List:
                                    <ul>
                                        @foreach (var room in Model.RoomInBookings)
                                        {
                                            if (room.BookRoomId == item.Id)
                                            {
                                                @foreach (var roomitem in Model.Room)
                                                {
                                                    if (room.RoomId == roomitem.Id)
                                                    {
                                                        <li style="list-style-type: none" class="card-text px-4">-Room Title: @roomitem.Title</li>
                                                    }
                                                }
                                            }
                                        }
                                    </ul>
                                </p>
                                <p class="card-text">Price: @item.Total.000đ </p>
                                <p class="card-text mb-4">Status In Order : @item.Status</p>
                                @if (item.Status != "Cancel")
                                {
                                    <form method="post" asp-page-handler="Cancel" asp-route-id="@item.Id">
                                        <div class="container float-left" style="margin-right: 20px">
                                            <div class="form-group">
                                                <input type="submit" value="Cancel" class="btn btn-primary" />
                                            </div>
                                        </div>
                                    </form>

                                }

                            </div>
                        </div>
                    </div>


                }
            </div>
        </div>





    </div>


</div>
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}
<script type="text/javascript">
        window.onload = function() {
            if ('@TempData["Message"]' != "") {
            alert('@TempData["Message"]');
            }
            };


            </script>