HotelWeb/Pages/AccountManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObject.Model;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using HotelWeb.Utils.FileUploadService;
using System.ComponentModel.DataAnnotations;
using HotelWeb.Validation;

namespace HotelWeb.Pages.AccountManagement
{
    public class EditModel : PageModel
    {
        private readonly IAccountRepository accountRepository;
        private readonly IFileUploadService fileUploadService;
        public EditModel(IAccountRepository _accountRepository, IFileUploadService _fileUploadService)
        {
            accountRepository = _accountRepository;
            fileUploadService = _fileUploadService;
        }
        [BindProperty]
        public Account Account { get; set; }


      
        [DataType(DataType.Upload)]
        [Display(Name = "Choose an image to upload")]
        [ProductImageValidation]
        [BindProperty]
        public IFormFile ImageFile { get; set; }


        public IActionResult OnGet(int id)
        {
            if (HttpContext.Session.GetString("ROLE") != "AD")
            {
                return RedirectToPage("./Index");
            }
            try
            {
                Account = accountRepository.GetProfile(id);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
          

           
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult>  OnPost()
        {
            try
            {
                Account acc = new Account
                {
                    Id = Account.Id,
                    Email = Account.Email,
                    Password = Account.Password,
                    Fullname = Account.Fullname,
                    Gender = Account.Gender,
                    Phone = Account.Phone,
                    IsEmployee = Account.IsEmployee,
                    Avartar = Account.Avartar,
                    Active = Account.Active
                };
                if (ImageFile != null)
                {
                    await fileUploadService.UploadFileAsync(ImageFile);
                    acc.Avartar = ImageFile.FileName;
                }
                accountRepository.UpdateMember(acc);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
          


            return RedirectToPage("./Index");
        }

      
    }
}

HotelWeb/Pages/CouponManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObject.Model;
using DataAccess.Repository;

namespace HotelWeb.Pages.CouponManagement
{
    public class EditModel : PageModel
    {
        private readonly ICouponRepository couponRepository;

        public EditModel(ICouponRepository _couponRepository)
        {
            couponRepository = _couponRepository;
        }

        [BindProperty]
        public Coupon Coupon { get; set; }

        public IActionResult OnGet(string id)
        {

            Coupon = couponRepository.GetCouponById(id);


            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public IActionResult OnPost()
        {

            couponRepository.UpdateCoupon(Coupon);


            return RedirectToPage("./Index");
        }
    }
}

HotelWeb/Pages/RoomManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObject.Model;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using HotelWeb.Utils.FileUploadService;
using System.ComponentModel.DataAnnotations;
using HotelWeb.Validation;

namespace HotelWeb.Pages.RoomManagement
{
    public class EditModel : PageModel
    {
        private readonly IRoomRepository roomRepository;
        private readonly IRoomTypeRepository roomTypeRepository;
        private readonly IFileUploadService fileUploadService;
        public EditModel(IRoomRepository _roomRepository, IRoomTypeRepository _roomTypeRepository, IFileUploadService _fileUploadService)
        {
            roomRepository = _roomRepository;
            roomTypeRepository = _roomTypeRepository;
            fileUploadService = _fileUploadService;
        }
        [BindProperty]
        public IList<RoomType> RoomTypeList { get; set; }
        [BindProperty]
        public Room Room { get; set; }

        [DataType(DataType.Upload)]
        [Display(Name = "Choose an image to upload")]
        [ProductImageValidation]
        [BindProperty]
        public IFormFile ImageFile { get; set; }

        public IActionResult OnGet(int id)
        {
            if (HttpContext.Session.GetString("ROLE") != "AD")
            {
                return RedirectToPage("./Index");
            }
            try {
                Room = roomRepository.GetRoomById(id);
                RoomTypeList = roomTypeRepository.GetRoomsType().ToList();
            }
            catch(Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
          


            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPost()
        {
            try
            {
                Room room = new Room
                {
                    Id = Room.Id,
                    Title = Room.Title,
                    Image = Room.Image,
                    Amount = Room.Amount,
                    Description = Room.Description,
                    RoomTypeId = Room.RoomTypeId,
                    Active = Room.Active,
              
                };
                if (ImageFile != null)
                {
                    await fileUploadService.UploadFileAsync(ImageFile);
                    room.Image = ImageFile.FileName;
                }
                roomRepository.UpdateRoom(room);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
        


            return RedirectToPage("./Index");
        }
    }
}

HotelWeb/Pages/RoomManagement/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BusinessObject.Model;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using HotelWeb.Utils.FileUploadService;
using System.ComponentModel.DataAnnotations;
using HotelWeb.Validation;

namespace HotelWeb.Pages.RoomManagement
{
    public class IndexModel : PageModel
    {
        private readonly IRoomRepository roomRepository;
        private readonly IRoomTypeRepository roomTypeRepository;
        private readonly IFileUploadService fileUploadService;
        private readonly IBookRoomRepository bookRoomRepository;
        private readonly IRoomInBookingRepository roomInBookingRepository;
        public IndexModel(IRoomRepository _roomRepository, IRoomTypeRepository _roomTypeRepository, IFileUploadService _fileUploadService, IBookRoomRepository _bookRoomRepository, IRoomInBookingRepository _roomInBookingRepository)
        {
            roomRepository = _roomRepository;
            roomTypeRepository = _roomTypeRepository;
            fileUploadService = _fileUploadService;
            bookRoomRepository = _bookRoomRepository;
            roomInBookingRepository = _roomInBookingRepository;
        }
        [BindProperty]
        public Room Room { get; set; }
        public IList<BookRoom> RoomBookingList { get; set; }
        [Required(ErrorMessage = " image can not be empty")]
        [DataType(DataType.Upload)]
        [Display(Name = "Choose an image to upload")]
        [ProductImageValidation]
        [BindProperty]
        public IFormFile ImageFile { get; set; }
        public IList<Room> RoomList { get; set; }
        public IList<RoomType> RoomTypeList { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }
        public DateTime today = DateTime.Now;
        [BindProperty]
        [DataType(DataType.Date)]
        public DateTime CheckOut { get; set; }
        public List<Room> first = new List<Room>();
        public IList<Room> RoomNotEmpty { get; set; }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("ROLE") != "AD")
            {
                return RedirectToPage("./Index");
            }
            try
            {
                CheckOut = DateTime.Now.AddDays(1);
             
                RoomList = roomRepository.GetRooms().ToList();
                RoomTypeList = roomTypeRepository.GetRoomsType().ToList();
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }

            return Page();
        }
        public async Task<IActionResult> OnPostCreate()
        {
            try
            {
                string filePath = await fileUploadService.UploadFileAsync(ImageFile);
                Room room = new Room
                {
                    Id = Room.Id,
                    Title = Room.Title,
                    Image = ImageFile.FileName,
                    Amount = Room.Amount,
                    Description = Room.Description,
                    RoomTypeId = Room.RoomTypeId,
                    Active = true,
                   
                    
                };
                roomRepository.AddRoom(room);
                return RedirectToPage("./Index");
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                return RedirectToPage("./Index");
            }


        }
        public IActionResult OnPostSearch([FromForm] string SearchString)
        {

            if (!string.IsNullOrEmpty(SearchString))
            {
                RoomList = roomRepository.SearchByName(SearchString.ToLower().Trim());
                RoomTypeList = roomTypeRepository.GetRoomsType().ToList();
            }
            else
            {
                RoomList = roomRepository.GetRooms().ToList();
                RoomTypeList = roomTypeRepository.GetRoomsType().ToList();
            }
            return Page();
        }
        public IActionResult OnPostUpdateActive(int id)
        {
            try
            {
              
                RoomBookingList = bookRoomRepository.GetStatus(today, today.AddMonths(1)).Where(x => x.Status == "BOOKED" || x.Status == "CHECKIN" || x.Status == "CHECKOUT").ToList();
                foreach (var item in RoomBookingList)
                {
                    RoomNotEmpty = roomInBookingRepository.GetRoomInBooking(item.Id);
                    first.AddRange(RoomNotEmpty);
                }
                if (RoomNotEmpty.Any(x => x.Id == id) == true)
                {
                    TempData["Message"] = "Not Maintenance because Room have Booked";
                    return RedirectToPage("./Index");

                }
                else
                {
                    Room room = roomRepository.GetRoomById(Room.Id);
                    roomRepository.UpdateActive(room.Id, room.Active);
                    TempData["Message"] = "Successfully";
                    return RedirectToPage("./Index");
                }
                

            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return RedirectToPage("./Index");

        }
        public IActionResult OnPostDelete(int id)
        {
            try
            {
                Room room = roomRepository.GetRoomById(id);
                roomRepository.DeleteRoom(room);

            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return RedirectToPage("./Index");

        }
    }
}

HotelWeb/Pages/RoomTypeManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObject.Model;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;

namespace HotelWeb.Pages.RoomTypeManagement
{
    public class EditModel : PageModel
    {
        private readonly IRoomTypeRepository roomTypeRepository;

        public EditModel(IRoomTypeRepository _roomRepository)
        {
            roomTypeRepository = _roomRepository;
        }

        [BindProperty]
        public RoomType RoomType { get; set; }

        public IActionResult OnGet(int id)
        {
            if (HttpContext.Session.GetString("ROLE") != "AD")
            {
                return RedirectToPage("./Index");
            }     
            try
            {
                RoomType = roomTypeRepository.GetRoomTypebyId(id);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public IActionResult OnPost()
        {
            try
            {
                roomTypeRepository.UpdateRoomType(RoomType);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }       
            return RedirectToPage("./Index");
        }
    }
}

HotelWeb/Pages/ServiceManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObject.Model;
using DataAccess.Repository;
using Microsoft.AspNetCore.Http;
using HotelWeb.Utils.FileUploadService;
using System.ComponentModel.DataAnnotations;
using HotelWeb.Validation;

namespace HotelWeb.Pages.ServiceManagement
{
    public class EditModel : PageModel
    {
        private readonly IServiceRepository serviceRepository;
        private readonly IServiceTypeRepository serviceTypeRepository;
        private readonly IFileUploadService fileUploadService;
        public EditModel(IServiceRepository _serviceRepository, IServiceTypeRepository _serviceTypeRepository, IFileUploadService _fileUploadService)
        {
            serviceRepository = _serviceRepository;
            serviceTypeRepository = _serviceTypeRepository;
            fileUploadService = _fileUploadService;
        }
        [BindProperty]
        public IList<ServiceType> ServiceTypeList { get; set; }
        [BindProperty]
        public Service Service { get; set; }
        [DataType(DataType.Upload)]
        [Display(Name = "Choose an image to upload")]
        [ProductImageValidation]
        [BindProperty]
        public IFormFile ImageFile { get; set; }
        public IActionResult OnGet(int id)
        {
            if (HttpContext.Session.GetString("ROLE") != "AD")
            {
                return RedirectToPage("./Index");
            }
            try
            {
                Service = serviceRepository.GetServiceById(id);
                ServiceTypeList = serviceTypeRepository.GetServicesType().ToList();
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }



            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPost()
        {
            try
            {
                Service service = new Service
                {
                    Id = Service.Id,
                    Title = Service.Title,
                    Image = Service.Image,
                    Amount = Service.Amount,
                    InStock = Service.InStock,
                    ServiceTypeId = Service.ServiceTypeId,
                   Active = Service.Active
                };
                if (ImageFile != null)
                {
                    await fileUploadService.UploadFileAsync(ImageFile);
                    service.Image = ImageFile.FileName;
                }
                serviceRepository.UpdateService(service);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return RedirectToPage("./Index");
        }
    }
}

HotelWeb/Pages/RoomManagement/Index.cshtml
@page
@model HotelWeb.Pages.RoomManagement.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<style>
    #Maintenance {
        padding: 0 !important;
        border: none !important;
        background: none !important;
        outline: none !important;
        margin: 0 !important;
        color: #BFE330 !important;
        width: 25px !important;
    }

    #Delete {
        padding: 0 !important;
        border: none !important;
        background: none !important;
        outline: none !important;
        margin: 0 !important;
        color: #FF0000 !important;
        width: 25px !important;
    }

    #Edit {
        padding: 0 !important;
        border: none !important;
        background: none !important;
        outline: none !important;
        margin: 0 !important;
        color: #2196F3 !important;
        width: 25px !important;
    }
</style>
<div class="container-fluid">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row mb-3">
                    <div id="header-title" class="col-sm-5">
                        <h2>User <b>Room</b></h2>
                    </div>
                    <div class="col-sm-4">
                        <form method="post" asp-page-handler="Search">
                            <div class=" row">
                                <div class="col-sm-9">
                                    <input type="text" class="form-control " id="searchBox" asp-for="SearchString" />
                                </div>
                                <div class="col-sm-3 mt-1">
                                    <button class="btn btn-primary" type="submit">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-3">
                        <button id="myBtn" class="btn btn-secondary"><i class="material-icons">&#xE147;</i> <span>Add New Room</span></button>
                    </div>
                </div>

                @if (Model.RoomList.Count != 0)
                {
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.RoomList[0].Image)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RoomList[0].Title)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RoomList[0].Description)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RoomList[0].Amount)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RoomList[0].RoomType)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RoomList[0].Active)
                                </th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.RoomList)
                            {

                                <tr>
                                    <td>
                                        <img src="~/img/@item.Image" alt="image" height="80" width="80" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Amount)
                                    </td>

                                    <td>
                                        @foreach (var item1 in Model.RoomTypeList)
                                        {
                                            if (item1.Id == item.RoomTypeId)
                                            {
                                                @item1.Title
                                            }
                                        }
                                    </td>
                                    <td>
                                        @if (item.Active == true)
                                        {
                                            <div>Actice</div>
                                        }
                                        else
                                        {
                                            <div>Maintenance</div>
                                        }
                                    </td>
                                    <td>
                                        <div class="row">
                                            <div class="col-sm-1">
                                                <form method="post" asp-page-handler="UpdateActive" asp-route-id="@item.Id" asp-route-checkout="@Model.CheckOut" onclick="return confirm('Are you sure you want to Update Active this?')" class="ml-0">
                                                    <div class="row">
                                                        <div>
                                                            <button id="Maintenance" type="submit" title="Maintenance" data-target="#exampleModal" data-toggle="modal">
                                                                <i class="material-icons">&#xe000;</i>
                                                            </button>
                                                            <input type="hidden" asp-for="@item.Id" />

                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                            <div class="">
                                                <a asp-page="./Edit" id="Edit" asp-route-id="@item.Id" class="" title="Settings" data-toggle="tooltip"><i id="icon" class="material-icons">&#xE8B8;</i></a>
                                            </div>
                                            @*    <div class="col-sm-2">
            <form method="post" asp-page-handler="Delete" asp-route-id="@item.Id" class="ml-0" onclick="return confirm('Are you sure you want to Delete this?')">
                <div class="row">
                    <div>
                        <button id="Delete" class="" type="submit" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE5C9;</i></button>
                    </div>
                </div>
            </form>
        </div>*@
                                        </div>
                                    </td>
                                </tr>
                            }
                        <tbody>
                    </table>
                }
                else
                {
                    <h1 class="text-danger"> No Result Value!</h1>
                }
            </div>
        </div>
    </div>


    <!-- Modal Add -->
    <div id="myModal" class="modal1">
        <div class="modal-content1">
            <span class="close">&times;</span>

            <form method="post" asp-page-handler="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Room.Id" class="control-label"></label>
                    <input asp-for="Room.Id" class="form-control" />
                    <span asp-validation-for="Room.Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Room.RoomTypeId" class="control-label"></label>
                    <select asp-for="Room.RoomTypeId" class="form-control">
                        @foreach (var item in Model.RoomTypeList)
                        {
                            <option value="@item.Id"> @item.Title</option>
                        }
                    </select>
                    <span asp-validation-for="Room.RoomTypeId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Room.Title" class="control-label"></label>
                    <input asp-for="Room.Title" class="form-control" />
                    <span asp-validation-for="Room.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label"></label>
                    <input asp-for="ImageFile" class="form-control" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Room.Description" class="control-label"></label>
                    <input asp-for="Room.Description" class="form-control" />
                    <span asp-validation-for="Room.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Room.Amount" class="control-label"></label>
                    <input asp-for="Room.Amount" class="form-control" />
                    <span asp-validation-for="Room.Amount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>


    </div><!-- Modal Delete -->
    <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header border-bottom-0">
                    <h5 class="modal-title" id="exampleModalLabel">Edit Foo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" asp-page-handler="Delete">

                    <div class="modal-body">
                        xoá chứ ?
                    </div>
                </form>
            </div>
        </div>
    </div>



</div>

<script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks the button, open the modal
    btn.onclick = function () {
        modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function () {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }


</script>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script type="text/javascript">
    window.onload = function() {
        if ('@TempData["Message"]' != "") {
            alert('@TempData["Message"]');
        }
    };
</script>
<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>